# Generated by Django 2.1.1 on 2018-09-06 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.SmallIntegerField(choices=[(0, 'Integer'), (1, 'String'), (2, 'Decimal'), (3, 'Boolean'), (4, 'File')])),
            ],
        ),
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('column_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.ColumnTable')),
            ],
        ),
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='eventtable',
            name='master_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.MasterTable'),
        ),
        migrations.AddField(
            model_name='columntable',
            name='master_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.MasterTable'),
        ),
    ]
