# Generated by Django 2.1.1 on 2018-09-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='eventtable',
            name='column_table',
        ),
        migrations.RemoveField(
            model_name='eventtable',
            name='master_table',
        ),
        migrations.DeleteModel(
            name='EventTable',
        ),
        migrations.AddField(
            model_name='columntable',
            name='value',
            field=models.ManyToManyField(to='master.ValueTable'),
        ),
    ]
