# Generated by Django 2.1.1 on 2018-10-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20180919_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuetable',
            name='kd_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
