# Generated by Django 2.1.1 on 2018-10-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_valuetable_kd_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuetable',
            name='kd_value',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
