# Generated by Django 2.1.1 on 2018-10-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20181001_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuetable',
            name='kd_value',
        ),
    ]
