# Generated by Django 2.1.1 on 2018-10-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_remove_valuetable_kd_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columntable',
            name='data_type',
            field=models.SmallIntegerField(choices=[(0, 'Integer'), (1, 'String'), (2, 'Decimal'), (3, 'Boolean'), (4, 'File'), (5, 'Date')]),
        ),
    ]
